---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - _misc/*
    - bin/*
    - vendor/**/*
  NewCops: enable

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/prawn-html.rb

Naming/MethodParameterName:
  Exclude:
    - lib/prawn_html/pdf_wrapper.rb

RSpec/ExampleLength:
  # default: 5
  Max: 15

RSpec/MultipleMemoizedHelpers:
  # default: 5
  Max: 6

RSpec/SubjectStub:
  Exclude:
    - spec/units/prawn_html/attributes_spec.rb

Style/OpenStructUse:
  Exclude:
    - lib/prawn_html/attributes.rb
    - spec/units/prawn_html/attributes_spec.rb
